services:
  failsafe:
    image: retrodesert/failsafe:latest
    container_name: failsafe
    stdin_open: true
    tty: true
    volumes:
      - ./logs:/failsafe/logs
      - ./actions:/failsafe/app/actions
    env_file:
      - .env
